testing two images with different build-configs

diff --git a/.github/workflows/build-containers.yml b/.github/workflows/build-containers.yml
--- a/.github/workflows/build-containers.yml
+++ b/.github/workflows/build-containers.yml
@@ -97,15 +97,30 @@ jobs:
         with:
           python-version: '3.x'
 
+      - name: Print matrix configuration
+        run: |
+          echo "Matrix configuration: ${{ matrix.config }}"
+
       - name: Print configuration
         run: |
           echo "Building ${{ matrix.name }} with configuration ${{ matrix.config }}"
           IFS='-' read -r BASE_OS OSG_SERIES BASE_REPO STANDARD_BUILD REPO_BUILD <<< "${{ matrix.config }}"
-          echo "base_os: $BASE_OS"
-          echo "osg_series: $OSG_SERIES"
-          echo "base_repo: $BASE_REPO"
-          echo "standard_build: $STANDARD_BUILD"
-          echo "repo_build: $REPO_BUILD"
+          echo "BASE_OS: $BASE_OS"
+          echo "OSG_SERIES: $OSG_SERIES"
+          echo "BASE_REPO: $BASE_REPO"
+          echo "STANDARD_BUILD: $STANDARD_BUILD"
+          echo "REPO_BUILD: $REPO_BUILD"
+
+      - name: Validate environment variables
+        run: |
+          echo "Validating environment variables:"
+          echo "BASE_OS: $BASE_OS"
+          echo "OSG_SERIES: $OSG_SERIES"
+          echo "BASE_REPO: $BASE_REPO"
+          if [ -z "$BASE_OS" ] || [ -z "$OSG_SERIES" ] || [ -z "$BASE_REPO" ]; then
+            echo "Error: One or more environment variables are not set."
+            exit 1
+          fi
 
       - name: Build Image
         run: |
