Fully implemented python script and workflow to build images

diff --git a/.github/workflows/build-containers.yml b/.github/workflows/build-containers.yml
--- a/.github/workflows/build-containers.yml
+++ b/.github/workflows/build-containers.yml
@@ -1,39 +1,44 @@
+---
 name: Build and push container images
 
-
 on:
- push:
- pull_request:
- workflow_dispatch:
- repository_dispatch:
-   types: [dispatch-build]
-
+  push:
+  pull_request:
+  workflow_dispatch:
+  repository_dispatch:
+    types: [dispatch-build]
 
 jobs:
- make-date-tag:
-   runs-on: ubuntu-latest
-   outputs:
-     dtag: ${{ steps.mkdatetag.outputs.dtag }}
-   steps:
-     - name: make date tag
-       id: mkdatetag
-       run: echo "dtag=$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT
+  make-date-tag:
+    runs-on: ubuntu-latest
+    outputs:
+      dtag: ${{ steps.mkdatetag.outputs.dtag }}
+    steps:
+      - name: make date tag
+        id: mkdatetag
+        run: echo "dtag=$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT
 
+  build-image-list:
+    runs-on: ubuntu-latest
+    outputs:
+      matrix: ${{ steps.set_matrix.outputs.matrix }}
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
- build-image-list:
-   runs-on: ubuntu-latest
-   outputs:
-     matrix: ${{ steps.set_matrix.outputs.matrix }}
-   steps:
-     - uses: actions/checkout@v3
-       with:
-         fetch-depth: 0
-
-
-     - id: image-list
-       run: |
-           ORG_DIR=opensciencegrid
-           if [[ $GITHUB_EVENT_NAME == 'pull_request' ]] ||
+      - id: image-list
+        run: |
+          ORG_DIR=opensciencegrid
+          # Get the list of files changed based on the type of event
+          # kicking off the GHA:
+          # 1. For the main branch, diff the previous state of main vs
+          #    the current commit
+          # 2. For other branches (i.e., on someone's fork), diff main
+          #    vs the current commit
+          # 3. For PRs, diff the base ref vs the current commit
+          # 4. For everything else (e.g., dispatches), build all images
+          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]] ||
               [[ $GITHUB_EVENT_NAME == 'push' ]]; then
                 if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
                     BASE=$(git merge-base origin/$GITHUB_BASE_REF HEAD)
@@ -42,265 +47,205 @@ jobs:
                 else
                     BASE=origin/main
                 fi
+                # List image root dirs where files have changed and the
+                # root dir exists. Example value:
+                # "opensciencegrid/vo-frontend opensciencegrid/ospool-cm"
                 images=$(git diff --name-only \
                                   "$BASE" \
                                   "$GITHUB_SHA" |
-                         egrep "^$ORG_DIR/" |
-                         cut -d/ -f -2 |
-                         sort |
-                         uniq |
-                         xargs -I {} find . -type d \
+                        egrep "^$ORG_DIR/" |
+                        cut -d/ -f -2 |
+                        sort |
+                        uniq |
+                        xargs -I {} find . -type d \
                                             -wholename ./{} \
                                             -printf "%P\n")
-           else
+          else
+                # List all image root dirs. Example value:
+                # "opensciencegrid/vo-frontend opensciencegrid/ospool-cm"
                 images=$(find $ORG_DIR -mindepth 1 \
-                                       -maxdepth 1 \
-                                       -type d \
-                                       -printf "$ORG_DIR/%P\n")
-           fi
+                                      -maxdepth 1 \
+                                      -type d \
+                                      -printf "$ORG_DIR/%P\n")
+          fi
+            image_json=$(echo -n "${images:-dummy}" | jq -Rcs '.|split("\n") | map(select(. != ""))')
+            echo "$image_json" > image_list.json
+            echo "images=$(echo $images | tr '\n' ' ')" >> $GITHUB_OUTPUT
+      - name: Display image list
+        run: cat image_list.json
 
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
 
-           image_json=$(echo -n "${images:-dummy}" | jq -Rcs '.|split("\n") | map(select(. != ""))')
-           echo "$image_json" > image_list.json
-           echo "images=$(echo $images | tr '\n' ' ')" >> $GITHUB_OUTPUT
+      - name: Run build-job-matrix script
+        id: run-python-script
+        run: python scripts/build-job-matrix.py ${{ steps.image-list.outputs.images }}
 
+      - name: Read JSON and set as output
+        id: set_matrix
+        run: |
+          json_content=$(cat scripts/grouped_output.json)
+          echo "::set-output name=matrix::$(echo $json_content | jq -c '.include')"
+      - name: Verify scripts/output.json
+        run: |
+          echo "Content of scripts/grouped_output.json:"
+          cat scripts/grouped_output.json
+  build:
+    runs-on: ubuntu-latest
+    needs: build-image-list
+    if: needs.build-image-list.outputs.images != '["dummy"]'
+    # Prevent a single build failure from killing the workflow.
+    # This is safe since subsequent pushes should fail on cache load
+    continue-on-error: true
+    strategy:
+      fail-fast: false
+      matrix:
+        include: ${{ fromJson(needs.build-image-list.outputs.matrix) }}
+    steps:
+      - uses: actions/checkout@v3
 
-     - name: Display image list
-       run: cat image_list.json
+      - name: Print raw matrix configuration
+        run: |
+          echo "Raw matrix configuration: ${{ matrix }}"
+      - name: Set environment variables
+        id: set-env-vars
+        run: |
+          CONFIG="${{ matrix.config }}"
+          BASE_OS=$(echo $CONFIG | awk -F'-' '{print $1}')
+          OSG_SERIES=$(echo $CONFIG | awk -F'-' '{print $2}')
+          BASE_REPO=$(echo $CONFIG | awk -F'-' '{print $3}')
+          CONTEXT="opensciencegrid/${{ matrix.name }}"
+          echo "BASE_OS=${BASE_OS}" >> $GITHUB_ENV
+          echo "OSG_SERIES=${OSG_SERIES}" >> $GITHUB_ENV
+          echo "BASE_REPO=${BASE_REPO}" >> $GITHUB_ENV
+          echo "CONTEXT=${CONTEXT}" >> $GITHUB_ENV
+      - name: Validate Environment Variables
+        run: |
+          echo "Validating environment variables:"
+          if [ -z "$BASE_OS" ] || [ -z "$OSG_SERIES" ] || [ -z "$BASE_REPO" ] || [ -z "$CONTEXT" ]; then
+            echo "Error: One or more environment variables are not set."
+            exit 1
+          else
+            echo "All required environment variables are set."
+          fi
+      - name: Build Image
+        continue-on-error: ${{ matrix.yum_repo == 'development' }}
+        uses: opensciencegrid/build-container-action@v0.6.0
+        with:
+          osg_series: ${{ env.OSG_SERIES }}
+          osg_repo: ${{ env.BASE_REPO }}
+          context: ${{ env.CONTEXT }}
+          base_os: ${{ env.BASE_OS }}
 
+  push:
+    runs-on: ubuntu-latest
+    if: >-
+      github.ref == 'refs/heads/main' &&
+      github.event_name != 'pull_request' &&
+      github.repository_owner == 'opensciencegrid' &&
+      needs.build-image-list.outputs.images != '["dummy"]'
+    needs: [make-date-tag, build-image-list, build]
+    strategy:
+      fail-fast: false
+      matrix:
+        include: ${{ fromJson(needs.build-image-list.outputs.matrix) }}
+    steps:
+      - uses: actions/checkout@v3
 
-     - name: Set up Python
-       uses: actions/setup-python@v2
-       with:
-         python-version: '3.x'
+      - name: Print raw matrix configuration
+        run: |
+          echo "Raw matrix configuration: ${{ matrix }}"
+      - name: Set environment variables
+        id: set-env-vars
+        run: |
+          CONFIG="${{ matrix.config }}"
+          BASE_OS=$(echo $CONFIG | awk -F'-' '{print $1}')
+          OSG_SERIES=$(echo $CONFIG | awk -F'-' '{print $2}')
+          BASE_REPO=$(echo $CONFIG | awk -F'-' '{print $3}')
+          CONTEXT="opensciencegrid/${{ matrix.name }}"
+          echo "BASE_OS=${BASE_OS}" >> $GITHUB_ENV
+          echo "OSG_SERIES=${OSG_SERIES}" >> $GITHUB_ENV
+          echo "BASE_REPO=${BASE_REPO}" >> $GITHUB_ENV
+          echo "CONTEXT=${CONTEXT}" >> $GITHUB_ENV
+      - name: Validate Environment Variables
+        run: |
+          echo "Validating environment variables:"
+          if [ -z "$BASE_OS" ] || [ -z "$OSG_SERIES" ] || [ -z "$BASE_REPO" ] || [ -z "$CONTEXT" ]; then
+            echo "Error: One or more environment variables are not set."
+            exit 1
+          else
+            echo "All required environment variables are set."
+          fi
+      - name: Push to Harbor (${{ env.OSG_SERIES }}-development)
+        if: env.OSG_SERIES != '23'
+        uses: opensciencegrid/push-container-action@main
+        with:
+          repo: development
+          osg_series: ${{ env.OSG_SERIES }}
+          context: ${{ env.CONTEXT }}
+          base_os: ${{ env.BASE_OS }}
+          registry_url: hub.opensciencegrid.org
+          registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
+          registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}
 
+      - name: Push to Harbor (${{ env.OSG_SERIES }}-testing)
+        if: always()
+        uses: opensciencegrid/push-container-action@main
+        with:
+          repo: testing
+          osg_series: ${{ env.OSG_SERIES }}
+          context: ${{ env.CONTEXT }}
+          base_os: ${{ env.BASE_OS }}
+          registry_url: hub.opensciencegrid.org
+          registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
+          registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}
 
-     - name: Run build-job-matrix script
-       id: run-python-script
-       run: python scripts/build-job-matrix.py ${{ steps.image-list.outputs.images }}
+      - name: Push to Harbor (${{ env.OSG_SERIES }}-release)
+        if: always()
+        uses: opensciencegrid/push-container-action@main
+        with:
+          repo: release
+          osg_series: ${{ env.OSG_SERIES }}
+          context: ${{ env.CONTEXT }}
+          base_os: ${{ env.BASE_OS }}
+          registry_url: hub.opensciencegrid.org
+          registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
+          registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}
 
+      - name: Push to Docker Hub (${{ env.OSG_SERIES }}-development)
+        if: always()
+        uses: opensciencegrid/push-container-action@main
+        with:
+          repo: development
+          osg_series: ${{ env.OSG_SERIES }}
+          context: ${{ env.CONTEXT }}
+          base_os: ${{ env.BASE_OS }}
+          registry_url: docker.io
+          registry_user: ${{ secrets.DOCKER_USERNAME }}
+          registry_pass: ${{ secrets.DOCKER_PASSWORD }}
 
-     - name: Read JSON and set as output
-       id: set_matrix
-       run: |
-         json_content=$(cat scripts/grouped_output.json)
-         echo "::set-output name=matrix::$(echo $json_content | jq -c '.include')"
+      - name: Push to Docker Hub (${{ env.OSG_SERIES }}-testing)
+        if: always()
+        uses: opensciencegrid/push-container-action@main
+        with:
+          repo: testing
+          osg_series: ${{ env.OSG_SERIES }}
+          context: ${{ env.CONTEXT }}
+          base_os: ${{ env.BASE_OS }}
+          registry_url: docker.io
+          registry_user: ${{ secrets.DOCKER_USERNAME }}
+          registry_pass: ${{ secrets.DOCKER_PASSWORD }}
 
-
-     - name: Verify scripts/output.json
-       run: |
-         echo "Content of scripts/grouped_output.json:"
-         cat scripts/grouped_output.json
-
-
- build:
-   runs-on: ubuntu-latest
-   needs: build-image-list
-   strategy:
-     fail-fast: false
-     matrix:
-       include: ${{ fromJson(needs.build-image-list.outputs.matrix) }}
-   outputs:
-     matrix: ${{ toJson(matrix) }}
-   steps:
-     - uses: actions/checkout@v3
-
-
-     - name: Print raw matrix configuration
-       run: |
-         echo "Raw matrix configuration: ${{ matrix }}"
-
-
-     - name: Set up Python
-       uses: actions/setup-python@v2
-       with:
-         python-version: '3.x'
-
-
-     - name: Print and set configuration
-       run: |
-         echo "Building ${{ matrix.name }} with configuration ${{ matrix.config }}"
-         CONFIG="${{ matrix.config }}"
-         BASE_OS=$(echo $CONFIG | awk -F'-' '{print $1}')
-         OSG_SERIES=$(echo $CONFIG | awk -F'-' '{print $2}')
-         BASE_REPO=$(echo $CONFIG | awk -F'-' '{print $3}')
-         STANDARD_BUILD=$(echo $CONFIG | awk -F'-' '{print $4}')
-         REPO_BUILD=$(echo $CONFIG | awk -F'-' '{print $5}')
-         echo "BASE_OS: $BASE_OS"
-         echo "OSG_SERIES: $OSG_SERIES"
-         echo "BASE_REPO: $BASE_REPO"
-         echo "STANDARD_BUILD: $STANDARD_BUILD"
-         echo "REPO_BUILD: $REPO_BUILD"
-         echo "BASE_OS=$BASE_OS" >> $GITHUB_ENV
-         echo "OSG_SERIES=$OSG_SERIES" >> $GITHUB_ENV
-         echo "BASE_REPO=$BASE_REPO" >> $GITHUB_ENV
-         echo "STANDARD_BUILD=$STANDARD_BUILD" >> $GITHUB_ENV
-         echo "REPO_BUILD=$REPO_BUILD" >> $GITHUB_ENV
-
-
-     - name: Validate environment variables
-       run: |
-         echo "Validating environment variables:"
-         if [ -z "$BASE_OS" ] || [ -z "$OSG_SERIES" ] || [ -z "$BASE_REPO" ]; then
-           echo "Error: One or more environment variables are not set."
-           exit 1
-         else
-           echo "All required environment variables are set."
-         fi
-
-
-     - name: Build Image
-       run: |
-         DEFAULT_TAG=$(echo s3-backup-${OSG_SERIES}-${BASE_REPO}-${GITHUB_RUN_NUMBER} | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]-')
-         docker build --build-arg BASE_OS=$BASE_OS \
-                      --build-arg BASE_OSG_SERIES=$OSG_SERIES \
-                      --build-arg BASE_REPO=$BASE_REPO \
-                      --tag $DEFAULT_TAG \
-                      --file opensciencegrid/${{ matrix.name }}/Dockerfile \
-                      opensciencegrid/${{ matrix.name }}
-
-
- push:
-   runs-on: ubuntu-latest
-   needs: build
-   if: github.event_name != 'pull_request'
-   steps:
-     - uses: actions/checkout@v3
-
-
-     - name: Set up Python
-       uses: actions/setup-python@v2
-       with:
-         python-version: '3.x'
-
-
-     - name: Parse build matrix
-       id: parse-matrix
-       run: echo "matrix=$(echo '${{ needs.build.outputs.matrix }}' | jq -c '.include')" >> $GITHUB_OUTPUT
-
-
-     - name: Print parsed matrix
-       run:
-         |
-         echo "Parsed matrix: ${{ steps.parse-matrix.outputs.matrix }}"
-
-
-     - name: Print and set configuration
-       run: |
-         echo "Pushing ${{ steps.parse-matrix.outputs.matrix }}"
-         for CONFIG in $(echo '${{ steps.parse-matrix.outputs.matrix }}' | jq -r '.[] | @base64'); do
-           _jq() {
-             echo ${CONFIG} | base64 --decode | jq -r ${1}
-           }
-
-
-           BASE_OS=$(_jq '.base_os')
-           OSG_SERIES=$(_jq '.osg_series')
-           BASE_REPO=$(_jq '.base_repo')
-           STANDARD_BUILD=$(_jq '.standard_build')
-           REPO_BUILD=$(_jq '.repo_build')
-
-
-           echo "BASE_OS: $BASE_OS"
-           echo "OSG_SERIES: $OSG_SERIES"
-           echo "BASE_REPO: $BASE_REPO"
-           echo "STANDARD_BUILD: $STANDARD_BUILD"
-           echo "REPO_BUILD: $REPO_BUILD"
-           echo "BASE_OS=$BASE_OS" >> $GITHUB_ENV
-           echo "OSG_SERIES=$OSG_SERIES" >> $GITHUB_ENV
-           echo "BASE_REPO=$BASE_REPO" >> $GITHUB_ENV
-           echo "STANDARD_BUILD=$STANDARD_BUILD" >> $GITHUB_ENV
-           echo "REPO_BUILD=$REPO_BUILD" >> $GITHUB_ENV
-
-
-           # Ensure tags are formatted correctly
-           TAG=$(echo "${BASE_OS}-${OSG_SERIES}-${BASE_REPO}-${STANDARD_BUILD}-${REPO_BUILD}" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]._-')
-           TAG=$(echo "$TAG" | sed 's/--*/-/g' | sed 's/^[-]*//;s/[-]*$//')
-
-
-           echo "Pushing image with tag: $TAG"
-
-
-           # Push images to registries
-           docker tag $DEFAULT_TAG hub.opensciencegrid.org/ppathu/opensciencegrid:$TAG
-           docker push hub.opensciencegrid.org/ppathu/opensciencegrid:$TAG
-
-
-           docker tag $DEFAULT_TAG docker.io/ppathu/opensciencegrid:$TAG
-           docker push docker.io/ppathu/opensciencegrid:$TAG
-         done
-
-
-     - name: Push to Harbor (${{ matrix.osg_series }}-development)
-       if: matrix.osg_series != '23'
-       uses: opensciencegrid/push-container-action@main
-       with:
-         repo: development
-         osg_series: ${{ matrix.osg_series }}
-         context: opensciencegrid/${{ matrix.name }}
-         base_os: ${{ matrix.base_os }}
-         registry_url: hub.opensciencegrid.org
-         registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
-         registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}
-
-
-     - name: Push to Harbor (${{ matrix.osg_series }}-testing)
-       if: always()
-       uses: opensciencegrid/push-container-action@main
-       with:
-         repo: testing
-         osg_series: ${{ matrix.osg_series }}
-         context: opensciencegrid/${{ matrix.name }}
-         base_os: ${{ matrix.base_os }}
-         registry_url: hub.opensciencegrid.org
-         registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
-         registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}
-
-
-     - name: Push to Harbor (${{ matrix.osg_series }}-release)
-       if: always()
-       uses: opensciencegrid/push-container-action@main
-       with:
-         repo: release
-         osg_series: ${{ matrix.osg_series }}
-         context: opensciencegrid/${{ matrix.name }}
-         base_os: ${{ matrix.base_os }}
-         registry_url: hub.opensciencegrid.org
-         registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
-         registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}
-
-     - name: Push to Docker Hub (${{ matrix.osg_series }}-development)
-       if: always()
-       uses: opensciencegrid/push-container-action@main
-       with:
-        repo: development
-        osg_series: ${{ matrix.osg_series }}
-        context: opensciencegrid/${{ matrix.name }}
-        base_os: ${{ matrix.base_os }}
-        registry_url: docker.io
-        registry_user: ${{ secrets.DOCKER_USERNAME }}
-        registry_pass: ${{ secrets.DOCKER_PASSWORD }}
-      
-     - name: Push to Docker Hub (${{ matrix.osg_series }}-testing)
-       if: always()
-       uses: opensciencegrid/push-container-action@main
-       with:
-         repo: testing
-         osg_series: ${{ matrix.osg_series }}
-         context: opensciencegrid/${{ matrix.name }}
-         base_os: ${{ matrix.base_os }}
-         registry_url: docker.io
-         registry_user: ${{ secrets.DOCKER_USERNAME }}
-         registry_pass: ${{ secrets.DOCKER_PASSWORD }}
-  
-     - name: Push to Docker Hub (${{ matrix.osg_series }}-release)
-       if: always()
-       uses: opensciencegrid/push-container-action@main
-       with:
-         repo: release
-         osg_series: ${{ matrix.osg_series }}
-         context: opensciencegrid/${{ matrix.name }}
-         base_os: ${{ matrix.base_os }}
-         registry_url: docker.io
-         registry_user: ${{ secrets.DOCKER_USERNAME }}
-         registry_pass: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Push to Docker Hub (${{env.OSG_SERIES }}-release)
+        if: always()
+        uses: opensciencegrid/push-container-action@main
+        with:
+          repo: release
+          osg_series: ${{ env.OSG_SERIES }}
+          context: ${{ env.CONTEXT }}
+          base_os: ${{ env.BASE_OS }}
+          registry_url: docker.io
+          registry_user: ${{ secrets.DOCKER_USERNAME }}
+          registry_pass: ${{ secrets.DOCKER_PASSWORD }}
